datasets:
  bixi:
    column_mapping:
      categorical_features:
        - 'ride_stations'
        - 'is_member'
      numerical_features:
        - 'distance_km'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
    reference_file: ./datasets/bixi_monitoring_06_22.csv
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
